CoLM-SYSU/CoLM202X

main/hydro/mod_soil_water.F90
fix a bug from VARIABLY_SATURATED_FLOW
=> Colm202 x v0.54

main/mod_mapping_grid2pset.F90, main/mod_mapping_pset2grid.F90, mksrfdata/aggregation_soil_parameters.F90, mksrfdata/mod_aggregation_LC.F90, mksrfdata/mod_aggregation_PFT.F90, mksrfdata/mod_hydrounit.F90, mksrfdata/mod_landpatch.F90, mksrfdata/mod_landpc.F90, mksrfdata/mod_landpft.F90, mksrfdata/mod_pixelsetshadow.F90, mksrfdata/mod_srfdata_restart.F90, share/mod_grid.F90, share/mod_landbasin.F90, share/mod_pixelset.F90, share/ncio_block.F90, share/ncio_serial.F90
1) Sort basins to make the results of the two mksrfdata runs the same;
2) Change the name of elements in pixelset to make them more readable.
=> Sort basins

mksrfdata/Makefile, mksrfdata/mksrfdata.F90, mksrfdata/mod_hydrounit.F90, mksrfdata/mod_landpatch.F90, mksrfdata/mod_patch2grid.F90, share/mod_landbasin.F90, share/mod_mapping_pset2grid.F90, share/mod_namelist.F90, share/mod_pixelset.F90
1) Add feature of unstructured grid. 
2) Add feature of using dominant patch type.
=> Unstructured grid & Using dominant patch type.

main/MOD_2D_Fluxes.F90, main/Makefile, main/mod_hist.F90, main/mod_hist_vector.F90, main/mod_unstructured_mesh.F90, postprocess/Makefile, postprocess/hist_vector2grid.F90, postprocess/mod_vector2grid.F90, share/mod_data_type.F90, share/mod_utils.F90, share/ncio_serial.F90
1) Add feature of writing vectors to history files; 
2) Add feature of mapping vectors to gridded data in original coordinate by postprocessing.
=> History of Vectors

main/LAKE.F90, main/LEAF_interception.F90, main/MOD_CaMa_Variables.F90, main/THERMAL.F90, main/colm_CaMaMod.F90, main/meltf.F90, main/rain_snow_temp.F90
Modified several files to be compatible for gfortran compiler. 
Delete additional spaces, and regulate code format.
=> Modified several files to be compatible for gfortran compiler.

main/mod_forcing.F90
Fix a bug in reading meteorological forcing.
=> fix bugs in mod_forcing.F90

main/mod_hist.F90, mksrfdata/mksrfdata.F90, mksrfdata/mod_mesh_filter.F90, run/gridbased_pearl_CMFD_igbp_100km.nml, share/mod_grid.F90, share/mod_mesh.F90, share/mod_namelist.F90, share/ncio_serial.F90
When defined GRIDBASED, mesh file (land mask file) is not necessary now, instead, resolutions can be used to define grid.
=> Mesh file in GRIDBASED mode is not necessary now.

Makefile, main/MOD_Glacier.F90, main/MOD_GroundTemperature.F90, main/MOD_LightningData.F90, main/MOD_Ozone.F90, main/MOD_PhaseChange.F90, main/MOD_Thermal.F90, main/URBAN/MOD_Urban_ImperviousTem.F90, main/URBAN/MOD_Urban_PerviousTem.F90, main/URBAN/MOD_Urban_RoofTem.F90
1. Rename MOD_GroundTem.F90 and MOD_Meltf.F90, including rename the module name. 
2. Add description for MOD_Ozone and MOD_LightningData.
=> Rename MOD_GroundTem.F90 and MOD_Meltf.F90. Add description for MOD_Ozone and MOD_LightningData.

main/MOD_AssimStomataConductance.F90, main/MOD_CropReadin.F90, main/MOD_Eroot.F90
Add description on MOD_AssimiStomataConductance, MOD_CropReadin and MOD_LightningData
=> Add description on MOD_AssimiStomataConductance, MOD_CropReadin and MOD_LightningData

include/define.h, main/BGC/MOD_BGC_Veg_CNVegStructUpdate.F90, main/CoLM.F90, main/CoLMDRIVER.F90, main/CoLMMAIN.F90, main/LULCC/MOD_Lulcc_Initialize.F90, main/MOD_AssimStomataConductance.F90, main/MOD_Hist.F90, main/MOD_LAIReadin.F90, main/MOD_LeafTemperature.F90, main/MOD_LeafTemperaturePC.F90, main/MOD_Ozone.F90, main/MOD_Thermal.F90, main/MOD_Vars_1DAccFluxes.F90, main/MOD_Vars_TimeInvariants.F90, main/MOD_Vars_TimeVariables.F90, main/URBAN/MOD_Urban_Flux.F90, mkinidata/MOD_DBedrockReadin.F90, mkinidata/MOD_IniTimeVar.F90, mkinidata/MOD_Initialize.F90, mksrfdata/Aggregation_DBedrock.F90, mksrfdata/MKSRFDATA.F90, mksrfdata/MOD_RegionClip.F90, mksrfdata/MOD_SingleSrfdata.F90, share/MOD_Namelist.F90
1. Move LAIFEEDBACK and BEDROCK switches to namelist
2. Move OzoneStress and OzoneData switches to namelist
=> Move Several switches from define.h to namelist

main/MOD_Aerosol.F90, main/MOD_Albedo.F90, main/MOD_SnowSnicar.F90, main/MOD_Vars_Global.F90
-mod(MOD_Aerosol.F90,MOD_Albedo.F90,MOD_SnowSnicar.F90): change dtime as input parameters; nlevsno -> maxsnl (CoLM Glboal variable).
-pretty(MOD_SnowSnicar.F90): code clean and prettified.
=> Change nlevsno and dtime as input parameters for albedo/snicar and clean the codes.

share/MOD_Pixelset.F90
=> Bug fixed in MOD_Pixelset.F90

Makefile, mksrfdata/MOD_SingleSrfdata.F90
fix a bug in SinglePoint Mode when making mksrfdata
=> fix a bug in SinglePoint Mode

mksrfdata/MOD_SingleSrfdata.F90
=> fix a bug in SinglePoint mode when reading LAI

main/LULCC/MOD_Lulcc_Initialize.F90, main/LULCC/MOD_Lulcc_Vars_TimeVariables.F90, main/MOD_Hist.F90, main/MOD_Vars_1DAccFluxes.F90, main/MOD_Vars_2DFluxes.F90, main/URBAN/MOD_Urban_Flux.F90, main/URBAN/MOD_Urban_GroundFlux.F90, main/URBAN/MOD_Urban_LAIReadin.F90, main/URBAN/MOD_Urban_LUCY.F90, main/URBAN/MOD_Urban_Thermal.F90, main/URBAN/MOD_Urban_Vars_2DFluxes.F90, main/URBAN/Urban_CoLMMAIN.F90, mkinidata/MOD_UrbanReadin.F90, mksrfdata/Aggregation_LAI.F90, mksrfdata/Aggregation_Urban.F90, share/MOD_Namelist.F90, share/MOD_TimeManager.F90
-mod(main/LULCC/ *.F90): fix bug of pc run and zi_soimm
-mod(main/URBAN/*.F90): rename popcell to pop_den, initialize vehc and meta, fix bug of LUCY
-mod(main/URBAN/MOD_Urban_Flux.F90): rewrite code of calculating cgimp and cgperl
-mod(mkinidata/MOD_UrbanReadin.F90): set pop_den=0 if not use LUCY, set fgper=1 if cv_gimp=0
-mod(main/URBAN/MOD_Urban_GroundFlux.F90): change calculate method of weighted qg
-mod(mksrfdata/Aggregation_Urban.F90): remove LUCY_COUN_, bug fix of aggregation pop_den if sumarea is 0
-mod(mksrfdata/Aggregation_Urban.F90): 1. fix bug when the pct_tree is fill value of rawdata(-999.), set the area of 500m grid to 0, do not aggregate. 2. add code of lai change
=> 1) Add LAI yearly change for urban model; 2) Add poeple density aggregation; 3) A bug fix for lulcc init.

main/CoLM.F90, main/CoLMDRIVER.F90, main/CoLMMAIN.F90, main/MOD_Aerosol.F90, main/MOD_SnowSnicar.F90, main/MOD_SoilSnowHydrology.F90, main/MOD_Vars_1DForcing.F90, share/MOD_Namelist.F90
-mod(CoLM.F90,CoLMDRIVER.F90,CoLMMAIN.F90,MOD_Aerosol.F90,MOD_Vars_1DForcing.F90,MOD_Namelist.F90):
Add aerosol readin and related namelist.
-mod(CoLM.F90):
Add timestep number for output.
-pretty(MOD_SnowSnicar.F90,MOD_SoilSnowHydrology.F90):
Add description for Macro MODAL_AER, code indent.
=> 1) Add aerosol readin and namelist; 2) Add timestep number for output.

Evaluation/scripts/geo/Makefiles_parallel.py, Evaluation/scripts/geo/Validation.py, Evaluation/scripts/geo/namelist_geo.txt
=> bugs fixed

Evaluation/scripts/geo/Validation.py
some observation variable units have been converted to mm/s
=> change the observation variables

main/CoLM.F90, main/LULCC/MOD_Lulcc_Initialize.F90, main/MOD_Vars_Global.F90, mkinidata/CoLMINI.F90, mksrfdata/MKSRFDATA.F90
Change subroutine Init_GlovalVars to Init_GlobalVars
=> Init_Gloval -> Init_Global

Evaluation/scripts/geo/Geo_information.py, Evaluation/scripts/geo/Makefiles_parallel.py, Evaluation/scripts/geo/Validation.py, Evaluation/scripts/geo/metrics.py, Evaluation/scripts/geo/run_geo.py, Evaluation/scripts/stn/Makefiles_parallel.py, Evaluation/scripts/stn/Station_information.py
1. bug fixed for CLM5 output evaluation
2. add function of plot metric map
3. bugs fixed
=> bugs fixed and plot metric function added

Makefile, main/CoLMMAIN.F90, main/MOD_Aerosol.F90, main/MOD_Albedo.F90, main/MOD_SnowSnicar.F90, mkinidata/MOD_IniTimeVariable.F90
-add(MOD_SnowSnicar.F90):
add function FreshSnowRadius (forc_t) to calculate fresh snow grain
size.
-mod(CoLMMAIN.F90,MOD_Aerosol.F90,MOD_Albedo.F90,MOD_IniTimeVariable.F90):
modified the related files due to above changes.
-mod(Makefile):
adjust for FreshSnowRadius addition.
=> Add fresh snow grain size function for SNICAR model.

share/MOD_SPMD_Task.F90
=> Update MOD_SPMD_Task.F90 to support coupling

Evaluation/scripts/geo/Makefiles_parallel.py, Evaluation/scripts/geo/Validation.py, Evaluation/scripts/geo/nml/namelist_geo_FullList.nml, Evaluation/scripts/geo/nml/test1.nml, Evaluation/scripts/geo/run_geo.py, Evaluation/scripts/stn/Makefiles_parallel.py, Evaluation/scripts/stn/Validation.py, Evaluation/scripts/stn/nml/namelist_stn_FullLIST.nml, Evaluation/scripts/stn/nml/test.nml, Evaluation/scripts/stn/run_stn.py
1. if evaluation items did not exist, pass it;
2. 0~360 and -180~180 longitude are supported.
3. additional test namelists added.
=> bugs fixed and functions added

main/CoLM.F90, main/MOD_Forcing.F90, main/MOD_Vars_1DAccFluxes.F90, main/MOD_Vars_TimeVariables.F90, mkinidata/MOD_Initialize.F90, run/gridbased_pearl_CMFD_igbp_100km.nml, share/MOD_Namelist.F90, share/MOD_NetCDFSerial.F90, share/MOD_RangeCheck.F90
1. print unit of variables;
2. use water table depth input if the file can be found;
3. print file name or variable name in nccheck subroutine (optional);
=> Some bugs fixed and minor modifications.

include/define.h, main/CoLM.F90, main/HYDRO/MOD_Hydro_RiverNetwork.F90, main/MOD_Forcing.F90, main/MOD_Hist.F90, main/MOD_HistVector.F90, main/MOD_Vars_1DAccFluxes.F90, main/MOD_Vars_2DFluxes.F90, mksrfdata/MOD_SingleSrfdata.F90, postprocess/HistConcatenate.F90, run/SinglePoint.nml, run/forcing/POINT.nml, share/MOD_5x5DataReadin.F90, share/MOD_NetCDFSerial.F90, share/MOD_NetCDFVector.F90, share/MOD_TimeManager.F90
1. Exception handling for reading netcdf files.
2.Some bugs fixed for SinglePoint.
=> Bugs fixed and code optimization.

main/CoLMMAIN.F90, main/MOD_LeafInterception.F90
=> minor bug fixed in leaf interception calculation

Makefile
Update Makefile to support static lib
after all other compilations, create a lib folder, link all .o (except for .o that contains PROGRAM)  and generate static lib file.
=> Update Makefile to support static lib

main/MOD_Vars_TimeVariables.F90, share/MOD_NetCDFBlock.F90
Initialization of ssrun and ssha had wrong dimensions. Bug fixed.
=> fix a initialize bug in PC

main/CoLM.F90, main/MOD_Forcing.F90, mksrfdata/MKSRFDATA.F90, mksrfdata/MOD_AggregationRequestData.F90, mksrfdata/MOD_LandPatch.F90, share/MOD_Namelist.F90, share/MOD_NetCDFSerial.F90
=> Some modifications.

main/MOD_LeafInterception.F90
bug fixed for noah-mp interception scheme
=> bug fixed for noah-mp interception scheme

main/CoLMMAIN.F90, main/MOD_LeafInterception.F90, main/MOD_LeafTemperature.F90, share/MOD_Namelist.F90
1. bugs fixed for available canopy interception schemes; now all options have been tested and can be used smoothly.
2. JULES canopy interception parameterization was added.
=> bugs fixed and new interception scheme added

mksrfdata/MOD_SingleSrfdata.F90, share/MOD_Namelist.F90
-mod(mksrfdata/MOD_SingleSrfdata.F90&share/MOD_Namelist.F90) delete urban marco
-mod(mksrfdata/MOD_SingleSrfdata.F90) fix bug of PC point case, due to PC being changed to PFT data structure, dimension of pft should be numpft, not N_PFT
=> fix conflict of single point case bewteen nature and urban

main/CoLMDRIVER.F90, main/CoLMMAIN.F90, main/HYDRO/MOD_Hydro_HillslopeNetwork.F90, main/HYDRO/MOD_Hydro_LateralFlow.F90, main/HYDRO/MOD_Hydro_RiverLakeFlow.F90, main/HYDRO/MOD_Hydro_RiverLakeNetwork.F90, main/HYDRO/MOD_Hydro_SoilWater.F90, main/HYDRO/MOD_Hydro_SubsurfaceFlow.F90, main/MOD_Glacier.F90, main/MOD_Hist.F90, main/MOD_NewSnow.F90, main/MOD_SoilSnowHydrology.F90, main/MOD_Vars_1DAccFluxes.F90, main/MOD_Vars_TimeInvariants.F90, main/MOD_Vars_TimeVariables.F90, mkinidata/MOD_IniTimeVariable.F90, mkinidata/MOD_Initialize.F90, mksrfdata/Aggregation_Topography.F90, mksrfdata/MKSRFDATA.F90, mksrfdata/MOD_SrfdataDiag.F90, share/MOD_Namelist.F90
1. water change due to evaporation is removed from wliq_icesno or wice_icesno for land ice type;
2. bug fixed in river-lake lateral flow;
3. add history variables of instantaneous water storage: wdsrf_inst (water on ground surface), wat_inst (water in soil), wa_inst (water deficit below soil levels)
=> Bugs fixed in water balance and lateral flow.

main/MOD_AssimStomataConductance.F90, main/MOD_LeafTemperature.F90, main/MOD_LeafTemperaturePC.F90, main/MOD_PlantHydraulic.F90
PFT and IGBP have been tested. 
Note: PC version got Water imbalance error. Need to resolve.
=> reorder PHS code to avoid excessive iterative solution

.gitignore, main/URBAN/MOD_Urban_BEM.F90, main/URBAN/MOD_Urban_Vars_TimeVariables.F90, main/URBAN/Urban_CoLMMAIN.F90
- Correct some comments; 
- prettify code; 
- add subroutine name when end subroutine SimpleBEM; 
- update .gitignore;
- Fix a bug in netsolar_urban call in Urban_CoLMMAIN.F90
=> Correct some comments

main/LULCC/MOD_Lulcc_MassEnergyConserve.F90, main/LULCC/MOD_Lulcc_TransferTrace.F90, main/MOD_LeafTemperaturePC.F90, share/MOD_Namelist.F90
-fix(MOD_Lulcc_TransferTrace.F90):
#ifdef CoLMDEBUG => RangeCheck
=> A macro name fix in LULCC and some codes format adjust.

main/CoLMMAIN.F90, main/DA/MOD_DA_GRACE.F90, main/MOD_Forcing.F90, main/MOD_Hist.F90, main/MOD_SoilSnowHydrology.F90, share/MOD_Namelist.F90
原湿地和冰川会出现水分累积在第一层的情形。
修改后，对冰川：第一层内多余的水分加入到降水中，第一层中多余的冰加入到降雪中；
对湿地：第一层多余的水转为地表积水。
=> Modifications to water balance.

main/MOD_UserSpecifiedForcing.F90, preprocess/Forcings/MSWX/step2_Merge_Data.sh, run/forcing/CLDAS.nml, run/forcing/CMFD.nml, run/forcing/CRUJRA.nml, run/forcing/ERA5LAND.nml, run/forcing/GDAS.nml, run/forcing/MSWX.nml, run/forcing/TPMFD.nml, run/forcing/WFDE5.nml, run/forcing/WFDEI.nml
forcing name list was updated to match the new version model
=> update focing namelist

include/define.h, main/CoLM.F90, main/CoLMDRIVER.F90, main/CoLMMAIN.F90, main/URBAN/Urban_CoLMMAIN.F90
-mod(CoLMMAIN.F90):
set the default aerosol deposition rate to 0 when no input is
provided.
-adj(CoLM.F90,CoLMDRIVER.F90,CoLMMAIN.F90):
code format adjust.
-fix(Urban_CoLMMAIN.F90):
add rss in Urban_CoLMMAIN.F90. [by @Wenzong Dong]
-mod(define.h):
remove URBAN_LCZ macro, modify notes for subgrid and urban
model macros.
=> 1) add rss in urban model; 2) modified define.h; 3) change default aerosol deposition rate; 4) code format adjust.

main/BGC/MOD_BGC_Vars_TimeInvariants.F90, main/BGC/MOD_BGC_Veg_CNFireLi2016.F90, mkinidata/MOD_Initialize.F90, run/create_clone
=> fix a bug that define g0 twice (medlyn model and fire model)

main/MOD_ForcingDownscaling.F90
-mod (main/MOD_ForcingDownscaling.F90)
adjust code according to the formation.
=> Code indent and clean for forcing downscaling

include/Makeoptions.SYSU-BaiduBoat_Parallel_with_zip, share/MOD_NetCDFVectorOneP.F90
VectorInOneFileP.f90 was updated to allow running in Parallel with zip mode.
=> bug fixed and add new configuration for SYSU-BaiduBoat

main/CoLMDRIVER.F90, main/CoLMMAIN.F90, main/MOD_Runoff.F90, main/MOD_SoilSnowHydrology.F90, main/MOD_UserSpecifiedForcing.F90, main/MOD_Vars_TimeInvariants.F90, main/URBAN/MOD_Urban_Hydrology.F90, main/URBAN/Urban_CoLMMAIN.F90, mkinidata/MOD_Initialize.F90, preprocess/Forcings/JRA3Q/step1_Get_Data.sh, preprocess/Forcings/JRA3Q/step2.1_mk_dlwrf_2003_2023.sh, preprocess/Forcings/JRA3Q/step2.2_mk_dswrf_2003_2023.sh, preprocess/Forcings/JRA3Q/step2.3_mk_pres_2003_2023.sh, preprocess/Forcings/JRA3Q/step2.4_mk_spfh2m_2003_2023.sh, preprocess/Forcings/JRA3Q/step2.5_mk_tmp2m_2003_2023.sh, preprocess/Forcings/JRA3Q/step2.6_mk_tprate_2003_2023.sh, preprocess/Forcings/JRA3Q/step2.6_mk_v_2003_2023.sh, preprocess/Forcings/JRA3Q/step2.7_mk_u_2003_2023.sh, preprocess/Forcings/JRA3Q/step2.8_mk_v_2003_2023.sh, run/China_Grid_50km_IGBP_VG.nml, run/Global_Grid_2x2_PFT_VG_BGC.nml, run/Global_Grid_50km_IGBP_CB_URBAN.nml, run/GreaterBay_Grid_10km_IGBP_VG.nml, run/RegChina_Grid_50km_IGBP_CB_LULCC.nml, share/MOD_Namelist.F90
1. add Simple VIC runoff scheme
2. add support for using JRA3Q forcing
=> Simple VIC runoff and JRA3Q forcing

CaMa/src/cmf_calc_diag_mod.F90, CaMa/src/cmf_calc_pthout_mod.F90, CaMa/src/cmf_ctrl_forcing_mod.F90, CaMa/src/cmf_ctrl_nmlist_mod.F90, CaMa/src/cmf_ctrl_output_mod.F90, CaMa/src/cmf_ctrl_vars_mod.F90, CaMa/src/cmf_drv_control_mod.F90, CaMa/src/cmf_opt_outflw_mod.F90, CaMa/src/cmf_utils_mod.F90, CaMa/src/yos_cmf_diag.F90, main/MOD_UserSpecifiedForcing.F90, preprocess/Forcings/CRA40/step1_Get_Data.sh, preprocess/Forcings/CRA40/step2.sh, run/CRA40_Grid_30km_IGBP_VG.nml, run/CRA40_Grid_50km_IGBP_VG.nml, run/Global_Grid_30km_IGBP_VG_CaMa.lsf, run/Global_Grid_30km_IGBP_VG_CaMa.nml, run/cama_flood.nml, run/forcing/CRA40.nml
1. much faster in the single precision mode when running CAMA.
2. CRA40 forcing support
3. bug fixed for bi-direction couple between colm and CAMA.
=> update : cama v1.13 +CRA40 forcing support

CaMa/map/CaMaMap4CoLM_glb_0.25in_0.25out, CaMa/src/MOD_CaMa_Vars.F90, CaMa/src/MOD_CaMa_colmCaMa.F90, CaMa/src/cmf_ctrl_damout_mod-org.F90, run/US_Grid_10km_IGBP_VG_CaMa.lsf, run/US_Grid_10km_IGBP_VG_CaMa.nml, run/cama_flood_10km.nml, run/cama_flood_US_30km.nml
cama-flood has been updated to 4.20
=> update to cama 4.20

Makefile, main/CoLM.F90, main/HYDRO/MOD_Catch_SubsurfaceFlow.F90, main/HYDRO/MOD_Hydro_SoilWater.F90, main/MOD_CheckEquilibrium.F90, main/MOD_CheckEquillibrium.F90, mksrfdata/MOD_SingleSrfdata.F90, share/MOD_Namelist.F90
1. Code for checking equilibrium state. Two diagnostic variables are calculated and written to file $hist/$casename_check_equilibrium.nc. The first one is total precipitation in a year ("total_precipitation"). The second one is the ratio of change in terrestrial water storage to total precipitation ("relative_tws_change"). Smaller value of "relative_tws_change" indicates better equilibrium state.
2. Optimization of VSF scheme.
=> 1. Code for checking equilibrium state. & 2. Optimization of VSF scheme.

main/MOD_FrictionVelocity.F90
Rewrite formula to avoid division by zero.
=> Bug fixed in FrictionVelocity. (solved by Yuan Hua)

Makefile, include/Makeoptions.land.gnu, mksrfdata/MKSRFDATA.F90, mksrfdata/MOD_MeshFilter.F90, share/MOD_Block.F90, share/MOD_Mesh.F90, share/MOD_Namelist.F90, share/MOD_Pixel.F90
1. Bug fixed in using landtype data to filter out ocean area.
2. Makefile optimizations (reported by Yiting Zhong)
3. Bug fixed in sorting elements.
=> Some bugs fixed & code optimization.

mkinidata/MOD_Initialize.F90
=> Update MOD_Initialize.F90:last last by zhwei

CaMa/src/MOD_CaMa_Vars.F90, CaMa/src/MOD_CaMa_colmCaMa.F90, CaMa/src/cmf_ctrl_maps_mod.F90, CaMa/src/cmf_ctrl_output_mod.F90, CaMa/src/yos_cmf_diag.F90, run/CaMa/cama_flood.nml, run/CaMa/cama_flood_10km.nml, run/CaMa/cama_flood_US_30km.nml
add output variable: outflw_ocean
=> add output of discharge to ocean

main/MOD_Forcing.F90, main/MOD_UserSpecifiedForcing.F90, run/forcing/CMFDv2.nml, run/forcing/ERA5.nml, run/forcing/ERA5LAND.nml, run/forcing/IsoGSM.nml
MOD_Forcing fixed by Yuan Huan to support CMFDv2 precipitation time format
add CMFDv2 and IsoGSM nml
modify MOD_UserSpecifiedForcing.F90
=> add CMFDv2 and IsoGSM Forcing support

main/CoLM.F90, main/MOD_Albedo.F90, main/MOD_Forcing.F90, main/MOD_LeafInterception.F90, share/MOD_RangeCheck.F90, share/MOD_SpatialMapping.F90
1. Reset initial albedo value from 0 to 1 in SNCAR module by Yuanhua.
2. Add physical constraint: tex_rain + tti_rain <= total rain input in Leaf_Interception module by Zhongwang.
3. fix a bug for 4D range check by Shupeng.
4. Enable conservation adjustment of convective and large scale precipitation for all precipitation downscaling schemes.
5. Add deallocate_part procedure in MOD_SpatialMapping.F90.
=> Some minor modifications

Makefile, main/MOD_Forcing.F90, main/MOD_ForcingDownscaling.F90, main/MOD_Vars_Global.F90, main/MOD_Vars_TimeInvariants.F90, mkinidata/MOD_Initialize.F90, mksrfdata/Aggregation_TopographyFactors_Simple.F90, mksrfdata/MKSRFDATA.F90, share/MOD_Namelist.F90
Modified files:
Makefile
main/MOD_Forcing.F90
main/MOD_ForcingDownscaling.F90
main/MOD_Vars_Global.F90
main/MOD_Vars_TimeInvariants.F90
mkinidata/MOD_Initialize.F90
mksrfdata/MKSRFDATA.F90
share/MOD_Namelist.F90
Add file:
mksrfdata/Aggregation_TopographyFactors_Simple.F90
=> Add a simple downscaling method for coupled model

main/BGC/MOD_BGC_Veg_CNVegStructUpdate.F90, mkinidata/MOD_Initialize.F90, run/scripts/diffcasecode.bash
Introduce a maximum LAI parameter (natlaimx=8) for nature vegetation type.
=> Set lai upper limit when activate LAIfeedback
